## Nornir Groups File 
---
NOKIA:
  username: 'admin'
  password: 'admin'
  platform: nokia_sros
  port: 22
  data:
    target: candidate
  connection_options:
    netconf:
      port: 830
      username: netconf
      password: NCadmin123
      extras:
        allow_agent: false
        hostkey_verify: false
        look_for_keys: false
    netmiko:
      enable: '123456'
    scrapli_netconf:
      port: 830
      username: netconf
      password: NCadmin123
      extras:
        auth_strict_key: False
        ssh_config_file: False
      platform: alu




